[tool] #will work
[tool.poetry]
name = "viper_Deployer"
version = "1.0"
description = "Automatic Deploy viper to Heroku"
authors = ["PerU-MoNsteR"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
